config/routes.rb
CmmTodo::Application.routes.draw do
  match '/login', :to => "users#login", :via => [:get]
  match '/signin', :to => "users#signin", :via => [:post]
  match '/logout', :to => "users#logout", :via => [:get]

  resources :users

	root :to => "main#index"
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :login, :password, :password_confirmation, :name
  attr_accessor :password_confirmation

  validates_uniqueness_of :login
  validates_confirmation_of :password

  has_many :tasks, :dependent => :destroy

  before_save :salting_password

  def self.authenticate(_login, _password)
    u = find_by_login(_login)
    u && u.password == Digest::SHA1.hexdigest("#{_password}:#{u.salt}") ? u: nil
  end

  protected
    def salting_password
      return unless self.changes.include?('password')
      self.salt = Digest::MD5.hexdigest(Time.now.to_f.to_s)
      self.password = Digest::SHA1.hexdigest("#{self.password}:#{self.salt}")
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery

	before_filter :set_current_user

	def set_current_user
		@current_user ||= login_from_session
	end

	def login_from_session 
		begin
			u = User.find(session[:user_id])
		rescue
			@current_user = nil
			session[:user_id] = nil
			return nil
		end
	end
	
	def login_required 
		if @current_user.blank?
			flash[:notice] = "forbidden."
			redirect_to login_path
		end
	end

	def notify_error(_obj)
		@error_obj = _obj
		render :template => "/main/error"
	end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/users_controller.rb
# encoding: UTF-8
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
	end

	def new 
		@user = User.new
	end

	def edit
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(params[:user])
		
		if @user.save
			@current_user = @user
			session[:user_id] = @user.id
		else
			flash[:notice] = "create user failed."
		end

		redirect_to root_path
	end
	
	def update
		@user = User.find(params[:id])

		#ToDo password 공백이면 업데이트 하지않게...

		if params[:user][:password].blank?
			params[:user].delete(:password)
			params[:user].delete(:password_confirmation)
		end

		if @user.update_attributes(params[:user])
			redirect_to root_path, notice:'User was successfully updated.' 
		else
			render :action => "edit"
		end
	end 

	def signin
		if u = User.authenticate(params[:user][:login], params[:user][:password]) 
			@current_user = u
			session[:user_id] = u.id

			redirect_to root_path
		else
			@current_user = nil
			session[:user_id] = nil
			reset_session
		
			flash[:notice] = "아이디와 패스워드를 확인하세요."
			redirect_to login_path
		end
	end

	def logout
		@current_user = nil
		session[:user_id] = nil
		reset_session

		redirect_to root_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def flash_messages
		fl = flash[:notice]
		flash[:notice] = nil
		fl
	end

	def logged_in?
		!@current_user.blank?
	end

end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CmmTodo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="flash_messages">
    <%= flash_messages %>
  </div>

  <div id="header">
    <%= link_to "Home", root_path %>
    <% if logged_in? %>
      <%= link_to "(#{@current_user.login})Logout", logout_path %>
      <%= link_to "UserInfo", user_path(@current_user) %>
    <% else %>
      <%= link_to "Login", login_path %>
      <%= link_to "New User", new_user_path %>
    <% end %>
  </div>

  <div id="section">
    <%= yield %>
  </div>

  <div id="footer">
  </div>

</body>
</html>

app/views/main/index.html.erb
main/index

app/views/users/_form.html.erb
<div class="general_form_wrapper">	
	<% if @user.errors.messages.length > 0 %>
		<div class="error_messages">
			<%= @user.errors.full_messages %>
		</div>
	<% end %>

	<%= form_for @user do |f| %>
		<div class="field">
			<%= f.label :login, "id:" %>
			<% if @user.new_record? %>
				<%= f.text_field :login, :class => "text" %>
			<% else %>
				<%= @user.login %>
			<% end %>
		</div>
		
		<div class="field">
			<%= f.label :password, "pw:" %>
			<%= f.password_field :password, :class => "text" %>
		</div>
		
		<div class="field">
			<%= f.label :password_confirmation, "pw_c:" %>
			<%= f.password_field :password_confirmation, :class => "text" %>
		</div>

		<div class="field">
			<%= f.label :name, "name:" %>
			<%= f.text_field :name, :class => "text" %>
		</div>

		<div class="actions">
			<%= f.submit("submit", :class => "submit") %>
		</div>
	<% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render 'form' %>
<%= link_to 'Back', user_path %>

app/views/users/login.html.erb
<h1>Login</h1>
<div class="general_form_wrapper">	
	<%= form_for :user, :url => signin_path do |f| %>
		<div class="field">
			<%= f.label :login, "id:" %>
			<%= f.text_field :login, :class => "text" %>
		</div>
		
		<div class="field">
			<%= f.label :password, "pw:" %>
			<%= f.password_field :password, :class => "text" %>
		</div>
		
		<div class="actions">
			<%= f.submit("login") %>
		</div>
	<% end %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render 'form' %>
<%= link_to 'Home', root_path %>

app/views/users/show.html.erb
<h1>User Info</h1>
<div class="general_form_wrapper">
	<div class="field">
		<label>id:</label>
		<%= @user.login %>
	</div>
	<div class="field">
		<label>name:</label>
		<%= @user.name %>
	</div>
	<%= link_to 'Edit', edit_user_path(@user) %>
	<%= link_to 'Home', root_path %>
</div>